# Generated by Django 3.1.1 on 2020-09-12 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='上传文件名')),
                ('mail_addr', models.CharField(max_length=50, verbose_name='邮箱')),
                ('message', models.TextField(blank=True, verbose_name='备注/留言')),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 4, 7, 585528, tzinfo=utc), verbose_name='上传时间')),
            ],
        ),
    ]
