# Generated by Django 2.2 on 2021-01-15 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_auto_20210115_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_record',
            name='export_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='导出文件名'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 11, 12, 59, 411321, tzinfo=utc), verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 11, 12, 59, 411277, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
