# Generated by Django 2.2 on 2021-01-15 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0007_auto_20210115_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_record',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 13, 15, 50, 663560, tzinfo=utc), verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 13, 15, 50, 663518, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
