# Generated by Django 2.2 on 2021-01-15 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0008_auto_20210115_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_record',
            name='export_msg',
            field=models.TextField(blank=True, default='空', verbose_name='转换信息'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 14, 30, 55, 32954, tzinfo=utc), verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 14, 30, 55, 32911, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
