# Generated by Django 2.2 on 2021-01-15 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0009_auto_20210115_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_record',
            name='export_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 15, 24, 26, 931471, tzinfo=utc), verbose_name='导出时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 15, 24, 26, 931494, tzinfo=utc), verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 15, 24, 26, 931426, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
