# Generated by Django 2.2 on 2021-01-15 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0010_auto_20210115_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_record',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 17, 27, 23, 960285, tzinfo=utc), verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='export_status',
            field=models.CharField(default='暂未导出，请耐心等待', max_length=255, verbose_name='转换状态'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='export_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 17, 27, 23, 960261, tzinfo=utc), verbose_name='导出时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 17, 27, 23, 960210, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
