# Generated by Django 2.2 on 2021-01-15 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0011_auto_20210116_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_record',
            name='is_deleted',
            field=models.CharField(default='空', max_length=50, verbose_name='导出文件删除状态'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 18, 15, 21, 554958, tzinfo=utc), verbose_name='下载时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='export_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 18, 15, 21, 554936, tzinfo=utc), verbose_name='导出时间'),
        ),
        migrations.AlterField(
            model_name='upload_record',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 18, 15, 21, 554889, tzinfo=utc), verbose_name='上传时间'),
        ),
    ]
